skip gwt for now -- needs new shapeless?
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:8: value ToTraversable is not a member of object shapeless.ops.hlist
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:8: value ToTraversable is not a member of object shapeless.ops.hlist
[specs2] [error] import shapeless.ops.hlist.{ToTraversable, ToList}
[specs2] [error] import shapeless.ops.hlist.{ToTraversable, ToList}
[specs2] [error]        ^
[specs2] [error]        ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:259: not found: type ToTraversable
[specs2] [error]   private implicit def toListAny[H <: HList]: ToList[H, Any] = new ToTraversable[H, List] {
[specs2] [error]                                                                    ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:259: type mismatch;
[specs2] [error]  found   : AnyRef{type Lub = Any}
[specs2] [error]  required: shapeless.ops.hlist.ToList[H,Any]
[specs2] [error]   private implicit def toListAny[H <: HList]: ToList[H, Any] = new ToTraversable[H, List] {
[specs2] [error]                                                                ^
[specs2] [warn] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:8: Unused import
[specs2] [warn] import shapeless.ops.hlist.{ToTraversable, ToList}
[specs2] [warn]                             ^
[specs2] [warn] one warning found
[specs2] [error] three errors found
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:259: not found: type ToTraversable
[specs2] [error]   private implicit def toListAny[H <: HList]: ToList[H, Any] = new ToTraversable[H, List] {
[specs2] [error]                                                                    ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:259: type mismatch;
[specs2] [error]  found   : AnyRef{type Lub = Any}
[specs2] [error]  required: shapeless.ops.hlist.ToList[H,Any]
[specs2] [error]   private implicit def toListAny[H <: HList]: ToList[H, Any] = new ToTraversable[H, List] {
[specs2] [error]                                                                ^
[specs2] [warn] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/specs2-9175fd7acdf2763bf5aac8e5c413778db1562ed8/gwt/src/main/scala/org/specs2/specification/script/GWT.scala:8: Unused import
[specs2] [warn] import shapeless.ops.hlist.{ToTraversable, ToList}
[specs2] [warn]                             ^
[specs2] [info] No documentation generated with unsuccessful compiler run
[specs2] [warn] two warnings found
[specs2] [error] three errors found
[specs2] [error] (gwt/compile:doc) Scaladoc generation failed
[specs2] [error] (gwt/compile:compileIncremental) Compilation failed